/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Alan Vega' at '22/12/15 20:28' with Gradle 2.6
 *
 * @author Alan Vega, @date 22/12/15 20:28
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
